Feature: landing page design
atlp-rwanda/commanders-medica-backoffice pull request #10
Opened 2024-07-06 14:49 UTC by fredshema

#### What does this PR do?

This PR includes designs and implantation of login and signup features.

#### Description of Task to be completed?

- Design landing page

#### How should this be manually tested?

Start the app with `npm run dev` and open the link. The landing page should be displayed

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

2024-07-06 17:40 UTC, justinmihigo requested changes
You did a great job this is really good, change that one thing

2024-07-06 17:40 UTC, justinmihigo commented on components/guest/landing/hero.tsx
> +            src="/images/doctors/doctor-1.png"
This image is to pixelated, use an a plugin that exports different assets in figma so that this images quality can be great.

2024-07-07 14:09 UTC, fredshema commented
@justinmihigo change the image with another that has a higher resolution, you can review it again

2024-07-08 05:45 UTC, justinmihigo approved these changes
Great job on this one

2024-07-09 08:12 UTC, merged